sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t allamneni/react-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true allamneni/react-docker-test npm test --coverage

after_success:
  - docker build -t dock-proj/multi-client ./client
  - docker build -t dock-proj/multi-nginx ./nginx
  - docker build -t dock-proj/multi-server ./server
  - docker build -t dock-proj/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push allamnenis/dock-proj/multi-client
  - docker push allamnenis/dock-proj/multi-nginx
  - docker push allamnenis/dock-proj/multi-server
  - docker push allamnenis/dock-proj/multi-worker
  

    
