sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t allamneni/react-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true allamneni/react-docker-test npm test --coverage

after_success:
  - docker build -t allamnenis/multi-client ./client
  - docker build -t allamnenis/multi-nginx ./nginx
  - docker build -t allamnenis/multi-server ./server
  - docker build -t allamnenis/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push allamnenis/multi-client
  - docker push allamnenis/multi-nginx
  - docker push allamnenis/multi-server
  - docker push allamnenis/multi-worker
 
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-194921650603'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

    
